stages:
  - bundle
  - build
  - deploy

job_bundle:
  stage: bundle
  image: maven:3.6.0-jdk-8
  script:
    - mvn install
  artifacts:
    paths:
      - target/

Job_build:
    image: docker:latest
    services:
        - docker:dind
    stage: build
    script:
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker build -t $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID .
        - docker push $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID

Job_deploy:

    stage: deploy
    tags: 
        - Pipeline-runner
    script:
      - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
      - docker pull $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID 
      - docker run --rm -d -p 8080:8080 $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID

